#- name: Enable EPEL Repository on CentOS 8
#  dnf:
#    name: epel-release
#    state: latest
#  become: True
# when: ansible_facts['os_family'] == 'RedHat'

- name: depend | Ensure dependencies are installed.
  dnf:
    pkg: [
                'jq',
                'redis',
                'nginx',
                'git',
                'gcc-c++',
                'npm',
                'device-mapper-persistent-data',
                'lvm2',
                'bzip2',
                'gcc',
                'openldap-devel',
                'xmlsec1-openssl',
                'autoconf',
                'automake',
                'binutils',
                'bison',
                'flex',
                'gcc',
                'gcc-c++',
                'gdb',
                'glibc-devel',
                'libtool',
                'make',
                'pkgconf',
                'pkgconf-m4',
                'pkgconf-pkg-config',
                'redhat-rpm-config',
                'rpm-build',
                'rpm-sign',
                'strace',
                'asciidoc',
                'byacc',
                'ctags',
                'diffstat',  
                'git',
                'intltool',
                'ltrace',
                'patchutils',
                'perl-Fedora-VSP',
                'perl-generators',
                'pesign',
                'source-highlight',
                'systemtap',
                'valgrind',
                'cmake',
                'expect',
                'rpmdevtools',  
                'rpmlint',
#               'ansible-collection-ansible-posix',
#               'supervisor'
                
        ]
  become: yes
  when: ansible_facts['os_family'] == 'RedHat'

- name: Install add  packages
  yum:
    name:
#     - xmlsec1-devel
      - libtool-ltdl-devel
      - mlocate
      - libpq-devel

    state: latest
    enablerepo: "powertools"
  become: True
  when: ansible_facts['os_family'] == 'RedHat'

- name: Add the group 'awx' with a specific gid and
  ansible.builtin.group:
    name: awx
    state: present
    gid: 1666
  become: True

- name: Add the user 'awx' with a specific uid and a primary group of 'awx'
  ansible.builtin.user:
    name: awx
    comment: awx service accout
    uid: 1666
    group: awx
  become: true 

- name: Create log dir
  file:
    path: /var/log/tower
    owner: awx
    group: awx
    state: directory
    mode: "u=rwx,g=rwx,o=r"
  become: yes

- name: Create  /var/lib/awx/rsyslog
  file:
    path: /var/lib/awx/rsyslog
    owner: awx
    group: awx
    state: directory
    mode: "u=rwx,g=rwx,o=r"
  become: yes

- name: Recursively change ownership of the directory /etc/tower/conf.d
  ansible.builtin.file:
    path: /etc/tower/conf.d
    state: directory
    recurse: yes
    owner: awx
    group: awx
  become: True


- name: set owner /run/tower
  ansible.builtin.file:
    path: /run/tower
    state: directory
    owner: awx
    group: nginx
  become: True

- name: Enable SELinux in enforcing mode
  selinux:
    policy: targeted
    state: permissive
  become: True

- name: adding nginx to group awx
  user:
    name: nginx
    groups: awx
    append: yes
  become: True
